# Generated by Django 4.1.7 on 2023-05-16 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('sname', models.CharField(max_length=100)),
                ('sid', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(3)])),
                ('addres', models.TextField()),
            ],
        ),
    ]
